### ISSUE TITLE
Add support for Swift Package Manager

### ISSUE THREAD

**Issue by xezero** [shakebugs/shake-ios#1]
Would it be possible to add support for integrating this framework with Swift Package Manager? The trend seems to be moving away from Cocoapods, as well as even Carthage.

**Comment by xezero** [comment]
Any updates on this by any chance? SPM 5.3 now supports binary targets! :)

**Comment by ekimia** [comment]
@xezero added this to my app, but looks like a small config issue:
`ERROR ITMS-90680: "Invalid directory. The bundle Payload/Level.app/PlugIns/Shake.framework is not contained in a correctly named directory. It should be under "Frameworks"`

Im a bit tied up so i havent had a chance to dig into this.
