### ISSUE TITLE
Pasting text as a description results in empty description being submitted

### ISSUE THREAD

**Issue by bdaz** [shakebugs/shake-ios#10]
It looks like there's a bug in the iOS SDK where if you start with the description empty and paste text into it, the report will have an empty description.

Steps to Reproduce:
0. Put text on your clipboard.
1. Shake
2. Paste text
3. Submit

Expected Result:
The pasted text is submitted as the description as part of the report.

Actual Result:
The description for the report is blank.

**Comment by p-shakebugs** [comment]
Thanks @bdaz for reporting this bug, we appreciate it ❤️ Our dev team will take care of it asap and hopefully publish it with the next release. Happy new year!

**Comment by david-decode** [comment]
@bdaz 

This has been fixed in the 14.1.2 release. 

Thanks for reporting.
