### ISSUE TITLE
Crash on SDK startup on version 14.1.1

### ISSUE THREAD

**Issue by hingarn** [shakebugs/shake-ios#12]
App crashes when attempting to start Shake SDK on the latest version (14.1.1). Works correctly on version 14.1.0.

CocoaPods: 1.10.1
Xcode: 12.4 
Simulator: iPhone 12, iOS 14.4

<img width="1036" alt="Screen Shot 2021-01-28 at 1 48 10 PM" src="https://user-images.githubusercontent.com/816542/106203178-d8b5f680-616f-11eb-8d02-502a03ad3992.png">

**Comment by david-decode** [comment]
Hi @hingarn 

We deprecated this method in the meantime and looks like we didn't check how it works with simulator.
I've added the issue in the backlog so somebody will be picking this up soon enough. Expect this fixed in one of the next releases.

Thanks for the report.

David

Shake Team

**Comment by hingarn** [comment]
Hi, @david-decode, the crash happens on a non-deprecated method as well. I did not include it here since it displays private keys.
