### ISSUE TITLE
Please put your React Native SDK on Github. 🙇

### ISSUE THREAD

**Issue by markymc** [shakebugs/shake-ios#14]
Hi guys, I see on https://www.npmjs.com/package/@shakebugs/react-native-shake that you're hosted on Bitbucket for your React Native SDK. However, when attempting to look at it (while logged into the Bitbucket), I just get a "We can't let you see this page" error. 

Is there a reason it's not hosted on Github? Please consider moving it here. Thanks!

**Comment by mstanic0** [comment]
Hi @markymc,

We don't have in plan to migrate our repository to Github for now.
However, we are thinking about open sourcing our Bitbucket React Native and Flutter repositories.
If we decide to do so, it will be visible on the Bitbucket very soon.

Regards

**Comment by markymc** [comment]
@mstanic0 Thanks for your reply.

Just so you know, it's not a great developer experience to have to go over to Bitbucket for an open source project to inspect the codebase and log issues. I'd strongly suggest you consider hosting on Github, even if it's a mirror of your Github one. 

As a note, we're experiencing issues upgrading to your latest React Native SDK on both iOS and Android, and we can't easily browse or share links to the native code to see what's going on and solve our problem.

**Comment by mstanic0** [comment]
Thanks for the suggestion, currently our CI/CD is depending on Bitbucket.
We would need to do refactor but currently are focused on delivering new features.

We have to see how that fits into our plan.
I'll update you here with the final decision.

**Comment by markymc** [comment]
Thanks. As I said, even just a mirror that we can inspect the code and log issues in would be good for now. :)

**Comment by markymc** [comment]
@mstanic0 We're now seeing this when trying to run our app on Android:

```
* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve com.shakebugs.android:shake:10.0.+.
     Required by:
         project :app > project :shakebugs_react-native-shake
      > Failed to list versions for com.shakebugs.android:shake.
         > Unable to load Maven meta-data from https://dl.bintray.com/shake/shake/com/shakebugs/android/shake/maven-metadata.xml.
            > Could not HEAD 'https://dl.bintray.com/shake/shake/com/shakebugs/android/shake/maven-metadata.xml'. Received status code 403 from server: Forbidden
```

Did something change?

**Comment by p-shakebugs** [comment]
Thanks for writing. Yup, take a look at this @markymc https://help.shakebugs.com/en/articles/5194807-our-builds-using-shake-are-failing-with-a-status-code-403-forbidden 👍

**Comment by ddoric-shake** [comment]
Hi @markymc, as from today we completed the process of open sourcing our React Native SDK and Flutter SDK repositories to Github so inspecting codebase and logging issues will be much easier from now on.
