### ISSUE TITLE
Shake SDK version is showing app version

### ISSUE THREAD

**Issue by BaDo2001** [shakebugs/shake-ios#19]
We have two apps developed by two separate teams, however we both encounter the same problem:
The Shake SDK Version on the Inspect tab is not the actual Shake version but the version of our app.

![image (5)](https://user-images.githubusercontent.com/41752867/147936532-2868c7c1-ceab-48fd-97a0-4ab15d9a9e5e.png)

**Comment by sgrahovar-shake** [comment]
Hey @BaDo2001.

We're aware of the issue and we're currently testing the fix, so it should be included in the next release.
Current workaround would be not to use apple's version and build manager until we fix the issue (that way, archiving the app won't change versions of all the framework to given app version).

We'll leave this open until we fix it, however you can also track progress on Feedback board by upvoting the issue there.

Thank you for reporting this!
