### ISSUE TITLE
Misleading activity description

### ISSUE THREAD

**Issue by ajRiverav** [shakebugs/shake-ios#2]
If the app silently reports a bug, the dashboard incorrectly states that the _User_ invoked Shake and submitted the bug, which is not true since it was a silent report that reported the bug. 

<img width="564" alt="image" src="https://user-images.githubusercontent.com/22076301/91116673-da2c4180-e65a-11ea-859b-df0191b981c3.png">

**Comment by p-shakebugs** [comment]
Misleading no more @ajRiverav — the log _"Shake was invoked and this feedback was submitted"_ is neutral now. Thanks once again for pointing it out.

**Comment by ajRiverav** [comment]
awesome @p-shakebugs
