### ISSUE TITLE
Shake is hanging when invoked 

### ISSUE THREAD

**Issue by ekimia** [shakebugs/shake-ios#24]
This happened recently so not sure whats going on here. When invoked from the screenshot, the UI is unresponsive. In Profiler, it looks like its hanging collecting activity information. V 15.3.0

**Comment by ekimia** [comment]
issue does not occur on 15.0.0

**Comment by tabita-shake** [comment]
Hi Evan, 

Thanks. We're looking into this and we'll update you when we have more info. 

Tabita

**Comment by mstanic-shake** [comment]
Please update to the latest version and check if it works for you. The issue should be fixed.
