### ISSUE TITLE
Outdated Releasees

### ISSUE THREAD

**Issue by embassem** [shakebugs/shake-ios#25]
Hello 
the release Page is Outdated 
it is missing releases since [15.0.2](https://github.com/shakebugs/shake-ios/releases/tag/15.0.2)
can you please update it

**Comment by mstanic-shake** [comment]
We didn't setup pipeline for this yet, so it is manually updated and sometimes it can take some time until we update it.
Our public documentation has releases section where you can take a look: https://docs.shakebugs.com/docs/ios/releases/
