### ISSUE TITLE
I'm experiencing App hanging issue on v 15.3

### ISSUE THREAD

**Issue by maxmiranda** [shakebugs/shake-ios#26]
Is this issue solved on verstion 16? 
<img width="849" alt="image" src="https://user-images.githubusercontent.com/24932260/228958069-f65ab10a-962a-4e7b-a55a-5780b378d636.png">

**Comment by p-shakebugs** [comment]
> Also is v16 out yet? I tried to install v16 and it was not working

As a founder who's awake late at night, I wanted to personally thank you for writing to us Max 😉 Our dev team will take a look at your ticket first thing tomorrow morning on our daily meeting.

AFAIK, native [iOS](https://docs.shakebugs.com/docs/ios/releases/#1600) and [Android](https://docs.shakebugs.com/docs/android/releases/#1600) SDK v16.0 are available as we speak 👍
And the SDK v16.0 for React Native and Flutter will be available in a few days.

**Comment by mstanic-shake** [comment]
Hi @maxmiranda, can you describe what is not working for you in version 16.

As far as I know we didn't work on app hangings in version 16 but I'm tagging here our iOS dev, he'll be available from Monday.
@david-halapir

**Comment by maxmiranda** [comment]
Hey @mstanic-shake  & @david-halapir. Here's my situation. I've been using 15.3 (but just updated to 16.0 so we'll see if that fixes anything). Upon further inspection, I realized the app hang events only happened twice on setupShake function (which is this code): 
```

Shake.configuration.isInvokedByShakeDeviceEvent = true
        Shake.configuration.isFloatingReportButtonShown = false
        Shake.configuration.shakingThreshold = 400
        Shake.configuration.isInvokedByScreenshot = true
        Shake.configuration.isInvokedByRightEdgePan = true
        Shake.configuration.isUserFeedbackEnabled = true
        Shake.configuration.isCrashReportingEnabled = true
        Shake.configuration.isAskForCrashDescriptionEnabled = true
        Shake.start(clientId: Constants.Shake.clientId, clientSecret: Constants.Shake.clientSecret)
```

I'm going to try to make some memory improvements to my app and see if that fixes these App Hangs.

**Comment by mstanic-shake** [comment]
Please update to the latest version and check if it works for you. The issue should be fixed.
