### ISSUE TITLE
Memory Leak in 16.1.0

### ISSUE THREAD

**Issue by cameronehrlich** [shakebugs/shake-ios#27]
Caused crashes on physical devices and allocated > 20gb of memory in the simulator.
Downgrading to 16.0.0 fixes the issue.
<img width="1610" alt="Screenshot 2023-05-08 at 6 34 01 PM" src="https://user-images.githubusercontent.com/1508740/236971885-cddff540-d87f-4c44-969b-4f92e42d2cf1.png">

**Comment by mstanic-shake** [comment]
Please update to the latest version and check if it works for you. The issue should be fixed.
