### ISSUE TITLE
App Privacy Manifest

### ISSUE THREAD

**Issue by Muesly** [shakebugs/shake-ios#32]
Apple is soon (Spring 2024) going to require every app to declare App Privacy Manifest files in their app submissions.  These declare the privacy use of the app including 3rd Party Libraries like Shake.  Are there any plans to add one to this library?

https://developer.apple.com/documentation/bundleresources/privacy_manifest_files

Thanks

**Comment by horsejockey** [comment]
@mstanic-shake any movement on this? This will become a requirement very soon.

**Comment by mstanic-shake** [comment]
@horsejockey A new version is released: https://docs.shakebugs.com/docs/ios/releases/

**Comment by sepbehroozi** [comment]
Hello @mstanic-shake 

While the latest version of the Shakebugs ios SDK contains the [PrivacyInfo.xcprivacy](https://github.com/shakebugs/shake-ios/blob/a78157df9435ac8acca8b2f84aeab92c968b649b/Sources/Shake.xcframework/ios-arm64/Shake.framework/PrivacyInfo.xcprivacy) file, it only declares reasons for `NSPrivacyAccessedAPICategoryFileTimestamp` and `NSPrivacyAccessedAPICategoryUserDefaults` categories.
However when I use [this script](https://github.com/Wooder/ios_17_required_reason_api_scanner) to scan the RRA usages in our codebase, it says the ShakeBugs SDK uses functions from the [Disk space APIs](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api#4278397)
Here's the output:
```
Used symbols in binary ./Frameworks/Shake.framework/Shake: NSFileSystemFreeSize, NSFileSystemSize, NSURLCreationDateKey, NSUserDefaults, stat
```

Any chance to consider adding the `NSPrivacyAccessedAPICategoryDiskSpace` to the privacy manifest?

**Comment by mstanic-shake** [comment]
@sepbehroozi 
Did you check this on the latest version? Disk usage was temporarily removed from the latest version as there was no option to select needed permission in xcode

**Comment by sepbehroozi** [comment]
> @sepbehroozi Did you check this on the latest version? Disk usage was temporarily removed from the latest version as there was no option to select needed permission in xcode

Hey @mstanic-shake 
Yes. We're using version `16.2.4`. To make sure I'm not dealing with a cached version, I just checked the XCFramework I downloaded from your Github, still got the same output (`NSFileSystemFreeSize`, `NSFileSystemSize`, `NSURLCreationDateKey`, `NSUserDefaults`, `stat`)

**Comment by mstanic-shake** [comment]
@sepbehroozi Please check 16.2.5 version, we had unused code which was probably detected by script.
