### ISSUE TITLE
App Hanging when received new notification 

### ISSUE THREAD

**Issue by abbasmoosavi** [shakebugs/shake-ios#33]
After install shake and implemented initial of it, App Hanging when received new notification from Firebase in active App state.
In background and inactive states is working fine, but when app is in active state, App hanging!

My XCODE return this from debug:
EXC_BAD_ACCESS
 
__52-[FIRMessagingRmqManager querySyncMessageWithRmqID:]_block_invoke

#app_hanging
#firebase
#crash

**Comment by mstanic-shake** [comment]
The same issue is reported on shake react native repo, closing it here.
https://github.com/shakebugs/shake-react-native/issues/5
