### ISSUE TITLE
Shake isn't shown up on Real device

### ISSUE THREAD

**Issue by tuyen-vuduc** [shakebugs/shake-ios#36]
I tried latest version 16.2.3. I can see the Shake report screen on Simulator, but when I tried on a real device, it doesnt work.

Do I have to configure any additional thing?

**Comment by mstanic-shake** [comment]
Hi @tuyen-vuduc,

It should work the same way on simulator and the device. Please make sure that you entered proper client id and client secret when starting shake and that your app is not archived.

If the problem still persists, please provide use more details so we can check it.

**Comment by tuyen-vuduc** [comment]
Hi @mstanic-shake ,

After several tries, finally Shake screen was shown up. I didn't find the exact way to shake once to show the screen yet. But it works.
