### ISSUE TITLE
Bitrise failed to compile. "error: exportArchive: ipatool failed with an exception"

### ISSUE THREAD

**Issue by RealNmae** [shakebugs/shake-ios#4]
In Xcode it compiles and runs. Version 11.6
In Bitrise it doesn't. Version 11.1

This is Bitrise log ouput:
`❌  error: exportArchive: ipatool failed with an exception: #<CmdSpec::NonZeroExitException: $ /Applications/Xcode.app/Contents/Developer/usr/bin/bitcode-build-tool -v -t /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin --sdk /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.1.sdk -o /var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/ipatool20200913-11727-fx8cxd/thinned-out/arm64/Payload/Livemetric.app/Frameworks/Shake.framework/Shake --generate-dsym /var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/ipatool20200913-11727-fx8cxd/thinned-out/arm64/Payload/Livemetric.app/Frameworks/Shake.framework/Shake.dSYM --strip-swift-symbols /var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/ipatool20200913-11727-fx8cxd/thinned-in/arm64/Payload/Livemetric.app/Frameworks/Shake.framework/Shake`

**Comment by ms-decode** [comment]
You should update Bitrise Xcode stack to the latest version for the workflow you are using.

Here is our help center article about that:
https://help.shakebugs.com/en/articles/4470125-i-can-t-build-an-app-with-the-xcode-when-using-shake
